//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.16 at 09:52:59 AM MDT 
//


package org.libresonic.restapi.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtistInfoBase", propOrder = {
    "biography",
    "musicBrainzId",
    "lastFmUrl",
    "smallImageUrl",
    "mediumImageUrl",
    "largeImageUrl"
})
@XmlSeeAlso({
    ArtistInfo.class,
    ArtistInfo2 .class
})
public class ArtistInfoBase {

    protected String biography;
    protected String musicBrainzId;
    protected String lastFmUrl;
    protected String smallImageUrl;
    protected String mediumImageUrl;
    protected String largeImageUrl;

    /**
     * Gets the value of the biography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiography() {
        return biography;
    }

    /**
     * Sets the value of the biography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiography(String value) {
        this.biography = value;
    }

    /**
     * Gets the value of the musicBrainzId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMusicBrainzId() {
        return musicBrainzId;
    }

    /**
     * Sets the value of the musicBrainzId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMusicBrainzId(String value) {
        this.musicBrainzId = value;
    }

    /**
     * Gets the value of the lastFmUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastFmUrl() {
        return lastFmUrl;
    }

    /**
     * Sets the value of the lastFmUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastFmUrl(String value) {
        this.lastFmUrl = value;
    }

    /**
     * Gets the value of the smallImageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmallImageUrl() {
        return smallImageUrl;
    }

    /**
     * Sets the value of the smallImageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmallImageUrl(String value) {
        this.smallImageUrl = value;
    }

    /**
     * Gets the value of the mediumImageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediumImageUrl() {
        return mediumImageUrl;
    }

    /**
     * Sets the value of the mediumImageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediumImageUrl(String value) {
        this.mediumImageUrl = value;
    }

    /**
     * Gets the value of the largeImageUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLargeImageUrl() {
        return largeImageUrl;
    }

    /**
     * Sets the value of the largeImageUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLargeImageUrl(String value) {
        this.largeImageUrl = value;
    }

}
